apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: release-demo-component-a
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: release-demo-component-a
    app.kubernetes.io/part-of: release-demo-app
  name: release-demo-component-a
  namespace: release-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: release-demo-component-a
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: release-demo-component-a
    spec:
      containers:
      - image: quay.io/damoreno/foobar:dev-code-with-quarkus
        imagePullPolicy: Always
        name: container-image
        resources: {}
status: {}
