apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  creationTimestamp: null
  name: release-demo-component-a
  namespace: release-demo
spec:
  params:
  - name: git-revision
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      annotations:
        build.appstudio.openshift.io/application: release-demo-app
        build.appstudio.openshift.io/build: "true"
        build.appstudio.openshift.io/component: release-demo-component-a
        build.appstudio.openshift.io/type: build
        build.appstudio.openshift.io/version: "0.1"
        pipelines.appstudio.openshift.io/type: build
      creationTimestamp: null
      generateName: release-demo-component-a-
      namespace: release-demo
    spec:
      params:
      - name: git-url
        value: https://github.com/sbose78/devfile-sample-code-with-quarkus
      - name: output-image
        value: quay.io/damoreno/foobar:dev-code-with-quarkus-$(tt.params.git-revision)
      pipelineRef:
        bundle: quay.io/redhat-appstudio/build-templates-bundle@sha256:2205a29208fa686b47f841819f7abedb64adb93935493693892d0e18bbdbb77e
        name: devfile-build
      workspaces:
      - name: workspace
        persistentVolumeClaim:
          claimName: appstudio
        subPath: release-demo-component-a/$(tt.params.git-revision)
      - name: registry-auth
        secret:
          secretName: redhat-appstudio-registry-pull-secret
    status: {}
status: {}
